### PR TITLE
Curl update: remove curl_formadd

### LINKED ISSUE #22: Fails to build
Hello, 

The c-vtapi was included in [Debian](https://tracker.debian.org/pkg/c-vtapi) on 2022-02-14 and recently failed during build due to some functions involving curl.

In the files lib/VtUrl.c, lib/VtComments.c and lib/VtFile.c I found the function curl_formadd, could you replace it with curl_mime_init()?

There are other errors that can be seen at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027611

Thanks for your work with c-vtapi!

### PR DESCRIPTION
**Pull request by karlhiramoto**
* fixes #22 
* TODO: only fixes file scan other functions need update too.

### CODE REVIEW

File: lib/VtComments.c [hunk 1]
```diff
@@ -180,28 +181,30 @@ int VtComments_add(struct VtComments *vt_comments, const char *comment) {
...
 
   /* Fill in the filename field */
-  ret = curl_formadd(&formpost,
-                     &lastptr,
-                     CURLFORM_COPYNAME, "comment",
-                     CURLFORM_COPYCONTENTS, comment,
-                     CURLFORM_END);
+  part = curl_mime_addpart(mime);
+  ret = curl_mime_data(part, comment, CURL_ZERO_TERMINATED);
+  curl_mime_name(part, "comment");
```
Comment (karlhiramoto) [inline lib/VtComments.c:200]:
```suggestion
  ret = curl_mime_name(part, "comment");
```

File: lib/VtComments.c [hunk 2]
```diff
@@ -180,28 +181,30 @@ int VtComments_add(struct VtComments *vt_comments, const char *comment) {
...
     VT_ERROR("Adding resource %s\n", vt_comments->resource);
 
   /* Fill in the filename field */
-  ret = curl_formadd(&formpost,
-                     &lastptr,
-                     CURLFORM_COPYNAME, "comment",
-                     CURLFORM_COPYCONTENTS, comment,
-                     CURLFORM_END);
+  part = curl_mime_addpart(mime);
+  ret = curl_mime_data(part, comment, CURL_ZERO_TERMINATED);
```
Comment (karlhiramoto) [inline lib/VtComments.c:199]: check return value

**Review by mgmacias95 — APPROVED** [review]
LGTM
